# -------------------------------------------
# _config.yml  —  properly formatted YAML
# -------------------------------------------
title: "Ali BaniAsad"
description: "Autonomous Systems & RL Researcher | CNAV Lab Head | Always learning."

baseurl: ""            # name of GitHub repository
url: "https://alibaniasad1999.github.io"
email: "alibaniasad1999@yahoo.com"

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "alibaniasad1999/"
google_scholar: "KeKpSvEAAAAJ&hl=en"
github: "alibaniasad1999"
orcid: "0009-0005-8094-1728"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html, div, p, ul, td, h1, h2, h3, h4, link, meta, footer, nav,
              img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
    # sort_by: order        # Jekyll will sort by this front-matter key
    # order:                # (optional) explicit list, kept for reference
    #   - Master.md
    #   - INS-AI.md
    #   - LQDG.md

# Sass
sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - _projects/project4.md
  - _projects/project5.md
  - _projects/project6.md
  - _projects/redirect.md
  - _projects/shortProject.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
